config/routes.rb
Rails.application.routes.draw do
  
  #中間テーブル(参加者)のアクション
  get 'user_tours/create'
  post 'user_tours/create'
  get 'user_tours/destroy'
  delete 'user_tours/destroy'
  
  #トップページアクション
  root 'pages#home'
  get 'pages/home'
  get 'pages/about'
  get 'pages/contact'
  
  #新規登録アクション
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  
  #問い合わせアクション
  get 'inquiries/new'
  get 'inquiries/create'
  get '/inquiries', to: 'inquiries#new'
  post '/inquiries', to: 'inquiries#create'
  
  #ログイン、ログアウトに関してのアクション
  get 'sessions/new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  #SNS認証ログインに関してのアクション
  get 'auth/:provider/callback', to: 'sessions#create'
  post 'auth/:provider/callback', to: 'sessions#create'
  
  #プロフィール画面に関してのアクション
  get 'users/:id/profiles', to: 'profiles#new', as: 'profiles_new'
  post 'users/:id/profiles', to: 'profiles#create'
  get 'users/:id/profile/show', to: 'profiles#show', as: 'profiles_show'
  get 'users/:id/profile/edit', to: 'profiles#edit', as: 'profiles_edit'
  patch 'users/:id/profile/edit', to: 'profiles#update'
  
  #ツアー検索一覧
  get '/tours', to: 'tours#index', as: 'all_tour'
  
  #ツアー詳細問い合わせアクション'
  get '/tours/:id/tour_contact', to: 'tour_contacts#new', as: 'tour_contacts_new'
  get '/tours/:id/tour_contact', to: 'tour_contacts#create'
  post '/tours/:id/tour_contact', to: 'tour_contacts#create', as: 'tour_contacts_create'
  
  #過去に参加したツアー一覧
  get '/users/:id/joined_past', to: 'users#joined_past', as: 'joined_past'
  
  #過去に開催したツアー一覧
  get '/users/:id/planned_past', to: 'users#planned_past', as: 'planned_past'
  
  resources :users
  
  resources :tours do
    resources :reviews
  end 
  
  namespace :admin do
    resources :users
  end 
  
end

app/models/user.rb
class User < ApplicationRecord
  before_save :email_downcase, unless: :uid?
  
  validates :name, presence: true, unless: :uid?, length: { maximum: 50 }
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, unless: :uid?, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false } #一意性の確認と、{大文字小文字の区別をしないという設定}
  
  VALID_PASSWORD_REGEX = /\A[a-z0-9]{8,32}+\z/i   #半角英数字8-32文字               
  validates :password, presence: true, format: { with: VALID_PASSWORD_REGEX }, allow_nil: true, unless: :uid?
  has_secure_password
  
  has_one :profile, dependent: :destroy
  has_many :user_tours, dependent: :destroy
  has_many :tours, dependent: :destroy
  has_many :joined_tours, through: :user_tours, source: 'tour' #ユーザーが参加するツアーリスト
  accepts_nested_attributes_for :user_tours, allow_destroy: true  #親モデルの更新の時、子モデルもまとめて更新できるようにする
  
  scope :join_tours_from_today, -> (id) { User.find(id).joined_tours.where("date > ?", Date.today).limit(5)} #今日以降の参加予定ツアー
  scope :plan_tours_from_today, -> (id) { User.find(id).tours.where("date > ?", Date.today).limit(5)} #今日以降の開催予定ツアー
  scope :joined_tours_past, -> (id) { User.find(id).joined_tours.where("date < ?", Date.today)} #昨日以前の過去に参加したツアー
  scope :planned_tours_past, -> (id) { User.find(id).tours.where("date < ?", Date.today)} #昨日以前の過去に開催したツアー
  
  #アドミンページのユーザー検索
  def self.search(search) 
    if search
      where(['name LIKE ?', "%#{search}%"])   
    else  
      all  
    end  
  end
  
  
  #SNS認証ログイン
  def self.find_or_create_from_auth(auth)
    provider = auth[:provider]
    uid = auth[:uid]
    name = auth[:info][:name]
    
    self.find_or_create_by(provider: provider, uid: uid) do |user|
      user.name = name
    end
  end
  
  def email_downcase
    self.email = email.downcase
  end 
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :admin_user
  
  helper_method :admin_user
  
  def index
    @search_users = User.all.search(params[:search])
    #@search_users = User.paginate(page: params[:page], per_page: 15)
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "ユーザーを削除しました"
    redirect_to(admin_users_path)
  end
  
  private
  
  #Adminユーザーかどうか
  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:show, :edit, :update]
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to @user #ログイン後のページと同じ
    else
      render :new
    end 
  end
  
  def show
    @user_join = User.join_tours_from_today(params[:id]) #参加予定のツアー
    @user_plan = User.plan_tours_from_today(params[:id]) #開催予定のツアー
  end
  
  def joined_past #参加したツアー
    @user_joined_past = User.joined_tours_past(params[:id]).paginate(page: params[:page], per_page: 10) 
  end 
  
  def planned_past #開催したツアー
    @user_planned_past = User.planned_tours_past(params[:id]).paginate(page: params[:page], per_page: 10) 
  end 

  private
  
   def user_params
     params.require(:user).permit(:name, :email, :password, :password_confirmation)
   end 
   
   
   
   
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/joined_past.html.erb
<div class="joined-past-wrapper">　　<!--ユーザーが過去に参加したツアー一覧 -->
  <div class="joined-past-container container">
    <h3 class="text-center">参加したツアー一覧</h3>
    <div class="row  justify-content-center">
      <div class="col-md-offset-3 col-md-6">
        <div class="tour-index-list">
          <% if @user_joined_past.exists? %>
            <% @user_joined_past.each do |tour| %>
              <div class="tour-box-list-past", data-turbolinks="false">
                <%= link_to tour.title, tour_path(id: tour.id) %><P>日時：<%= l tour.date %></P>
              </div>
            <% end %>
          <% else %>
            <h4>まだ<%= current_user.name %>さんが参加したツアーはありません</h4>
          <% end %>
          <%= will_paginate @user_joined_past, :previous_label => ' &lt 前へ', :next_label => '次へ &gt' %><br>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="signup-wrapper">
  <div class="signup-container container">
    <h3 class="text-center">Sign Up</h3>
    <div class="row  justify-content-center">
      <div class="col-xl-4 col-md-5 col-sm-6 col-10">
        <%= form_for @user, url: signup_path do |f| %>
          <%= render 'layouts/error_messages', model: f.object  %>
          <div class="form-group">
            <%= f.label :name, "氏名" %>
            <%= f.text_field :name, class: 'input-form form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :email, "メールアドレス" %>
            <%= f.email_field :email, class: 'input-form form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :password, "パスワード" %>
            <%= f.password_field :password, class: 'input-form form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :password_confirmation, "パスワード(確認用)" %>
            <%= f.password_field :password_confirmation, class: 'input-form form-control' %>
          </div>
          <div>
            <%= f.submit "登録", class: "btn btn-primary" %>
          </div>
        <% end %>
        <%= link_to "ログインはこちら", login_path %>  
      </div>
    </div>
  </div>
</div>

app/views/users/planned_past.html.erb
<div class="planned-past-wrapper"> <!--ユーザーが過去に開催したツアー一覧 -->
  <div class="planned-past-container container">
    <h3 class="text-center">開催したツアー一覧</h3>
    <div class="row  justify-content-center">
      <div class="col-md-offset-3 col-md-6">
        <div class="tour-index-list">
          <% if @user_planned_past.exists? %>
            <% @user_planned_past.each do |tour| %>
              <div class="tour-box-list-past", data-turbolinks="false">
                <%= link_to tour.title, tour_path(id: tour.id) %><P>日時：<%= l tour.date %></P>
              </div>
            <% end %>
          <% else %>
            <h4>まだ<%= current_user.name %>さんが開催したツアーはありません</h4>
          <% end %>
          <%= will_paginate @user_planned_past, :previous_label => ' &lt 前へ', :next_label => '次へ &gt' %><br>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="user-top-wapper">
  <div class="user-top-container container">
    <div class="top-title">
      <h1>FREE WALKING TOUR</h1>
      <h2>IN JAPAN</h2>
      <h1>ENJOY TOURS WITH THE LOCALS</h1>
    </div>
  </div>
  <div class="prfile-wapper">
    <p><%= current_user.name %>さんのプロフィール</p>
    <span class="side-image-size">
      <%= image_tag current_user.profile.image.to_s, class: "side-image-size" if !current_user.profile.nil? %>
      <%= image_tag "person.png", class: "side-image-size" if current_user.profile.nil? %><br>
    </span>
    <p>＜お名前＞</p>
    <%= current_user.name %><br>
    <p>＜プロフィール文＞</p>
    <% if current_user.profile.nil? %>
      <p>プロフィール文がありません</p>
    <% else %>
      <%= current_user.profile.body %><br>
    <% end %>
  </div>
  <div class="row">
    <div class="col-lg-7 col-md-6">
      <div class="tour-search-container">
        <h5>ツアー検索！</h5>
        <p>都道府県、または都市名を入力してください</p> <!--文字列部分一致検索 -->
        <%= form_tag(all_tour_path, method: :get) do %>
          <div class="tour-search-form">
            <%= text_field_tag :search, params[:search] %>
            <%= submit_tag "検索", :address => nil %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="col-lg-4 col-md-5">
      <div class="tour-make-container">
        <h5>ツアーを開催！</h5>
        <%= link_to new_tour_path do %>
          <button class="btn plan-btn">ツアーを計画する</button>
        <% end %>
      </div>
    </div>
    <div class="col-sm-10">
      <div class="your-plan-container">
        <h5><%= current_user.name %>さんの予定表</h5>
        <div class="joinning">
          <h5>◆参加予定のツアー</h5>
          <% if @user_join.exists? %>
            <% @user_join.each do |tour| %> <!--ユーザーが参加するツアー一覧 -->
              <div class="join-tour-box-list", data-turbolinks="false",> <!--リンク先でturbolinksを無効にする(google map表示のため) -->
                <%= link_to tour.title, tour_path(id: tour.id) %><P>日時：<%= l tour.date %></P>
              </div>
            <% end %>
          <% else %>
            <p>参加予定のツアーはありません</p>
          <% end %>
        </div>  
        <div class="planning">
          <h5>◆開催予定のツアー</h5>
          <% if @user_plan.exists? %>
            <% @user_plan.each do |tour| %>　<!--ユーザーが開催するツアー一覧 -->
              <div class="plan-tour-box-list", data-turbolinks="false">
                <%= link_to tour.title, tour_path(id: tour.id) %><P>日時：<%= l tour.date %></P>
              </div>
            <% end %>
          <% else %>
            <p>開催予定のツアーはありません</p>
          <% end %>
        </div>
      </div>
      <div class="your-plan-container">
        <h5><%= current_user.name %>さんの過去のアクティビティ</h5>
        <h6>参加したツアーのレビューを書きましょう！</h6>
        <div class="joined_tour">
          <p>過去に参加したツアーの一覧は<%= link_to "こちら", joined_past_path(id: current_user.id) %></p>
          
          <div class="planned_tour">
          <p>過去に開催したツアーの一覧は<%= link_to "こちら", planned_past_path(id: current_user.id) %></p>
        </div>
      </div>
    </div>
  </div>
</div>