config/routes.rb
Rails.application.routes.draw do
  
  #中間テーブル(参加者)のアクション
  get 'user_tours/create'
  post 'user_tours/create'
  get 'user_tours/destroy'
  delete 'user_tours/destroy'
  
  #トップページアクション
  root 'pages#home'
  get 'pages/home'
  get 'pages/about'
  get 'pages/contact'
  
  #新規登録アクション
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  
  #問い合わせアクション
  get 'inquiries/new'
  get 'inquiries/create'
  get '/inquiries', to: 'inquiries#new'
  post '/inquiries', to: 'inquiries#create'
  
  #ログイン、ログアウトに関してのアクション
  get 'sessions/new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  #SNS認証ログインに関してのアクション
  get 'auth/:provider/callback', to: 'sessions#create'
  post 'auth/:provider/callback', to: 'sessions#create'
  
  #プロフィール画面に関してのアクション
  get 'users/:id/profiles', to: 'profiles#new', as: 'profiles_new'
  post 'users/:id/profiles', to: 'profiles#create'
  get 'users/:id/profile/show', to: 'profiles#show', as: 'profiles_show'
  get 'users/:id/profile/edit', to: 'profiles#edit', as: 'profiles_edit'
  patch 'users/:id/profile/edit', to: 'profiles#update'
  
  #ツアー検索一覧
  get '/tours', to: 'tours#index', as: 'all_tour'
  
  #ツアー詳細問い合わせアクション'
  get '/tours/:id/tour_contact', to: 'tour_contacts#new', as: 'tour_contacts_new'
  get '/tours/:id/tour_contact', to: 'tour_contacts#create'
  post '/tours/:id/tour_contact', to: 'tour_contacts#create', as: 'tour_contacts_create'
  
  #過去に参加したツアー一覧
  get '/users/:id/joined_past', to: 'users#joined_past', as: 'joined_past'
  
  #過去に開催したツアー一覧
  get '/users/:id/planned_past', to: 'users#planned_past', as: 'planned_past'
  
  resources :users
  
  resources :tours do
    resources :reviews
  end 
  
  namespace :admin do
    resources :users
  end 
  
end

app/models/tour.rb
class Tour < ApplicationRecord
  validates :user_id, presence: true
  validates :title, presence: true, length: { maximum: 30 }
  validates :detail, presence: true, length: { maximum: 1500 }
  validates :address, presence: true
  validate :tour_day #空白と過去の日付は指定できない。下部にメソッドあり
  
  #ツアー一覧はツアー開催日順に表示する
  default_scope -> { order(date: :asc) }
  
  
  #gmapについて
  geocoded_by :address #addressカラムを基準に緯度経度を算出する
  after_validation :geocode, if: :address_changed? #住所変更時に緯度経度も変更する
  
  belongs_to :user
  has_many :user_tours
  has_many :joined_users, through: :user_tours, source: 'user' #ツアーに参加するユーザーリスト
  has_many :tour_contacts
  has_many :reviews
  has_many :reviewed_users, through: :reviews, source: 'user' #レビューを書いたユーザーリスト
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true #削除フラグで削除できるようallow_destroy: trueをつける
  
  scope :from_today, -> {where("date > ?", Date.today)}
  
  #ツアー検索
  def self.search(search) #self.はTour.を意味する
    if search
      where(['title LIKE ?', "%#{search}%"]) #検索とaddressの部分一致を表示する
    else
      all
    end
  end
  
  def tour_day
    validate_date = Date.tomorrow
    if date == nil || date < validate_date.beginning_of_day
      errors.add(:date, "は明日以降を選択してください")
    end
  end 
end
 

app/controllers/tours_controller.rb
class ToursController < ApplicationController
  before_action :find_id, only: [:show, :edit, :update]
  
  def index
    @search_tours = Tour.from_today.search(params[:search]).paginate(page: params[:page], per_page: 10)
  end 
  
  def new
    @tour = Tour.new
    @tour.images.new
  end

  def create
    @tour = Tour.new(tour_params)
    @tour.user_id = current_user.id
    if @tour.save
      images_params[:images].each do |img|
        @image = Image.new
        @image.tour_id = @tour.id
        @image.src = img
        @image.save
      end 
      redirect_to tour_path(@tour.id)
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @tour.update(tour_params)
      @tour.images.destroy_all
      images_params[:images].each do |img|
        @image = Image.new
        @image.tour_id = @tour.id
        @image.src = img
        @image.save
      end 
      flash[:success] = "ツアー内容をを変更しました"
      redirect_to tour_path(@tour.id)
    else
      render :edit
    end
  end

  def destroy
    Tour.find(params[:id]).destroy
    redirect_to user_path(current_user.id), info: 'ツアーを削除しました'
  end
  
  private
  
    def tour_params
      params.require(:tour).permit(:user_id, :title, :date, :detail, :latitude, :longitude, :address)
    end
    
    def images_params
      params.require(:tour).permit(images: [])
    end
    
    def find_id
      @tour = Tour.find(params[:id])
    end 
    
end

app/helpers/tours_helper.rb
module ToursHelper
  
end

app/views/tours/edit.html.erb
<div class="tour-edit-wrapper">
  <div class="tour-edit-container container">
    <h3 class="text-center">ツアー内容の変更</h3>
    <div class="row  justify-content-center">
      <div class="col-md-offset-3 col-md-6">
        <%= form_for @tour, url: tour_path do |f| %>
          <%= render 'layouts/error_messages', model: f.object %>
          <div class="tour-title">
            <%= f.label :title, "◆ツアー名" %>
            <%= f.text_field :title, class: 'tour-input-form form-control' %>
          </div>
          <div class="tour-date">
            <p><%= f.label :date, "◆ツアー開催日時" %>　※ツアー当日の作成はできません </p>
            <%= f.datetime_field :date, class: "datetime-input form-control" %>
          </div>
          <div class="tour-detail">
            <%= f.label :detail, "◆ツアーの詳細" %>
            <%= f.text_field :detail, class: 'tour-input-form form-control' %>
          </div>
          <div class="tour-address">
            <%= f.label :address, "◆ツアーの集合場所" %>
            <%= f.text_field :address, class: 'tour-input-form form-control' %>
          </div>
          <div class="tour-images">
            <%= f.label :images, "◆ツアーに関する写真" %>
            <p>ツアーで回る場所の写真や、過去のツアーの写真をアップロードできます</p>
            <%= f.file_field :images, :multiple => true %>
          </div>
          <div>
            <%= f.submit "変更内容を登録する", class: "btn btn-updated" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/tours/index.html.erb
<div class="tour-index-wrapper">
  <div class="tour-index-container container">
    <h3 class="text-center">検索ツアー一覧</h3>
    <div class="row  justify-content-center">
      <div class="col-md-offset-3 col-md-6">
        <div class="tour-index-list">
          <% @search_tours.each do |tour| %>
            <div class="index-tour-box-list", data-turbolinks="false">
              <%= link_to tour.title, tour_path(id: tour.id) %><P>開催日時：<%= l tour.date %></P>
            </div>
          <% end %>
          <%= will_paginate @search_tours, :previous_label => ' &lt 前へ', :next_label => '次へ &gt' %><br>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/tours/new.html.erb
<div class="tour-new-wrapper">
  <div class="tour-new-container container">
    <h3 class="text-center">開催するツアーの作成</h3>
    <div class="row  justify-content-center">
      <div class="col-sm-offset-3 col-sm-6">
        <%= form_for @tour, url: tours_path do |f| %>
          <%= render 'layouts/error_messages', model: f.object %>
          <div class="tour-title">
            <%= f.label :title, "◆ツアー名" %>
            <p>※件名や観光地名を含めることで、ツアー検索で見つけやすくなります</p>
            <%= f.text_field :title, class: 'tour-input-form form-control' %>
          </div>
          <div class="tour-date">
            <p><%= f.label :date, "◆ツアー開催日時"%>　※ツアー当日の作成はできません </p>
            <%= f.datetime_field :date, class: "datetime-input form-control" %>
          </div>
          <div class="tour-detail">
            <%= f.label :detail, "◆ツアーの詳細" %>
            <%= f.text_area :detail, rows: 5, class: 'tour-input-form form-control' %>
          </div>
          <div class="tour-address">
            <%= f.label :address, "◆ツアーの集合場所" %>
            <%= f.text_field :address, class: 'tour-input-form form-control' %>
          </div>
          <div class="tour-images">
            <%= f.label "◆ツアーに関する写真" %>
            <p>ツアーで回る場所の写真や、過去のツアーの写真をアップロードできます<br>※必ず1枚以上アップロードしてください(8枚まで)</p>
            <%= f.file_field :images, :multiple => true %>
          </div>
          <div>
            <%= f.submit "登録する" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/tours/show.html.erb
<% content_for(:body_attributes) do %>　<!--　このページでtourbolinksを無効化する -->
    data-turbolinks="false"
<% end %>
<div class="tour-wrapper">    
  <div class="tour-show-container container">
    <h3 class="text-center">ツアーインフォメーション</h3>
    <div class="row  justify-content-center">
      <div class="col-sm-offset-3 col-sm-6">
        <div class="tour-title-show">
          <h5>＜ツアー名＞</h5>
          <%= @tour.title %>
        </div>
        <div class="tour-guid-show">
          <h5>＜ツアー主催者＞</h5>
          <% if logged_in? && has_profile? %>
            <%= link_to @tour.user.name, profiles_show_path(@tour.user.id) %>
          <% else %>
            <%= @tour.user.name %>
          <% end %>
        </div>
        <div class="tour-date-show">
          <h5>＜ツアー開催日時＞</h5>
          <%= l @tour.date %>
        </div>
        <div class="tour-detail-show">
          <h5>＜ツアー内容＞</h5>
          <%= @tour.detail %>
        </div>
        <div class="tour-address-show">
          <h5>＜集合場所＞</h5>
          <%= @tour.address %>
          <div id="map">
            <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['MAP_API_KEY'] %>"></script>
            <script>
              function map_canvas() {
                var data = new Array();
                data.push({
                  lat: <%= @tour.latitude %>, //緯度
                  lng: <%= @tour.longitude %>, //経度
                  content: '集合場所' //情報ウィンドウ
                });
                var latlng = new google.maps.LatLng(data[0].lat, data[0].lng);
                var opts = {
                  zoom: 15,
                  center: latlng,
                  mapTypeId: google.maps.MapTypeId.ROADMAP
                };
                var map = new google.maps.Map(document.getElementById("map"), opts);
                var markers = new Array();
                  for (i = 0; i < data.length; i++) {
                    markers[i] = new google.maps.Marker({
                      position: new google.maps.LatLng(data[i].lat, data[i].lng),
                      map: map
                    });
                    markerInfo(markers[i], data[i].content);
                  }
              }
              function markerInfo(marker, name) {
                new google.maps.InfoWindow({
                  content: name
                }).open(marker.getMap(), marker);
              }
              google.maps.event.addDomListener(window, 'load', map_canvas);
            </script>
          </div>
        </div>
        <div class="tour-images-show">
          <h5>＜このツアーに関する写真＞</h5>
          <div id="carousel-1" class="carousel slide">
            <div class="carousel-inner">
              <% unless @tour.images.nil? %>
                <% count = 0 %>
                <% @tour.images.each do |image| %>
                  <% if count == 0 %>
                    <div class="carousel-item active">
                      <div class="d-block w-100"><%= image_tag image.src.to_s, class: "slide-image" %></div>
                    </div>
                  <% else %>
                    <div class="carousel-item">
                      <div class="d-block w-100"><%= image_tag image.src.to_s, class: "slide-image" %></div>
                    </div>
                  <% end %>
                  <% count += 1 %>
                <% end %>
              <% end %>
            </div>
            <a class="carousel-control-prev" href="#carousel-1" role="button" data-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carousel-1" role="button" data-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>
          </div>
        </div>
        <% if logged_in? && @tour.user_id == current_user.id %>
          <div class="tour-btn">
            <%= link_to "ツアー内容を変更する", edit_tour_path %>
          </div>
          <div class="tour-btn">
            <%= link_to "ツアーを削除する", tour_path, method: :delete %>
          </div>
        <% else %>
          <div class="tour-contact">
            <h5>＜お問い合わせ＞</h5>
            <P>このツアーに関してのお問い合わせは<%= link_to "こちら", tour_contacts_new_path %></P>
          </div>
          <% if @tour.joined_users.include?(current_user) %> <!--ツアーの参加者リストにcurrent_userがいたら以下を実行 -->
            <%= link_to user_tours_destroy_path(tour_id: @tour.id) do %>
              <button class="btn plan-btn", data-turbolinks="false">このツアーの参加をキャンセルする</button> <!-- data-turbolinks="falseはリンク先のmapを表示させるためのもの -->
            <% end %>
          <% else %>
            <%= link_to user_tours_create_path(tour_id: @tour.id) do %>
              <button class="btn plan-btn", data-turbolinks="false">このツアーに参加する</button>
            <% end %>
          <% end %>
          <div class="write-review">
            <% if !@tour.reviewed_users.include?(current_user) %> <!--レビューしたユーザーの中にcurrent_userがいなかったら以下を実行 -->
              <%= link_to "このツアーのレビューを書く", new_tour_review_path(tour_id: @tour.id) %>
            <% end %>
          </div>
        <% end %>
        <div class="star-rate">
          <p>＜このツアーの総合評価＞</p>
          <% if @tour.reviews.present? %>
            <script>
              $('.star-rate').raty({
                size: 40,
                starOff:  '<%= asset_path('star-off.png') %>',
                starOn : '<%= asset_path('star-on.png') %>',
                starHalf: '<%= asset_path('star-half.png') %>',
                half: true,
                readOnly: true,
                score: <%= @tour.reviews.average(:rate).to_f.round(1) %>,
              });
            </script>
            <%= link_to "口コミを見る", tour_reviews_path(tour_id: @tour.id) %>
          <% else %>
           <p>評価がありません</p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>