config/routes.rb
Rails.application.routes.draw do
  
  #中間テーブル(参加者)のアクション
  get 'user_tours/create'
  post 'user_tours/create'
  get 'user_tours/destroy'
  delete 'user_tours/destroy'
  
  #トップページアクション
  root 'pages#home'
  get 'pages/home'
  get 'pages/about'
  get 'pages/contact'
  
  #新規登録アクション
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  
  #問い合わせアクション
  get 'inquiries/new'
  get 'inquiries/create'
  get '/inquiries', to: 'inquiries#new'
  post '/inquiries', to: 'inquiries#create'
  
  #ログイン、ログアウトに関してのアクション
  get 'sessions/new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  #SNS認証ログインに関してのアクション
  get 'auth/:provider/callback', to: 'sessions#create'
  post 'auth/:provider/callback', to: 'sessions#create'
  
  #プロフィール画面に関してのアクション
  get 'users/:id/profiles', to: 'profiles#new', as: 'profiles_new'
  post 'users/:id/profiles', to: 'profiles#create'
  get 'users/:id/profile/show', to: 'profiles#show', as: 'profiles_show'
  get 'users/:id/profile/edit', to: 'profiles#edit', as: 'profiles_edit'
  patch 'users/:id/profile/edit', to: 'profiles#update'
  
  #ツアー検索一覧
  get '/tours', to: 'tours#index', as: 'all_tour'
  
  #ツアー詳細問い合わせアクション'
  get '/tours/:id/tour_contact', to: 'tour_contacts#new', as: 'tour_contacts_new'
  get '/tours/:id/tour_contact', to: 'tour_contacts#create'
  post '/tours/:id/tour_contact', to: 'tour_contacts#create', as: 'tour_contacts_create'
  
  #過去に参加したツアー一覧
  get '/users/:id/joined_past', to: 'users#joined_past', as: 'joined_past'
  
  #過去に開催したツアー一覧
  get '/users/:id/planned_past', to: 'users#planned_past', as: 'planned_past'
  
  resources :users
  
  resources :tours do
    resources :reviews
  end 
  
  namespace :admin do
    resources :users
  end 
  
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :logged_in_user
  before_action :find_id, only: [:show, :edit, :update]
  def new
    @review = Review.new
    @review.tour_id = params[:tour_id] #newのURIにtour_idがあるため、そのparamsのtour_idをインスタンス変数@reviewのtour_idに代入する
  end

  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    @review.tour_id = params[:tour_id]
    if @review.save!
     flash[:success] = "レビューを投稿しました"
     redirect_to tour_path(@review.tour_id)
    else
      flash.now[:danger] = "レビューを投稿に失敗しました"
    end 
  end

  def index
    @review = Review.id_index(tour_id: params[:tour_id]).paginate(page: params[:page], per_page: 5) #tour_idごとの一覧を表示する
   
  end

  def show
  end

  def edit
  end
  
  def update
    if @review.update!(review_params)
      flash[:success] = "レビュー内容をを変更しました"
      redirect_to tour_path(@review.tour.id)
    else
      render :edit
    end
  end

  def destroy
    @review = Review.find(params[:id]).delete
    redirect_to tour_path(@review.tour.id)
    flash[:info] = 'レビューを削除しました'
  end
  
  private
    def review_params
      params.require(:review).permit(:tour_id, :user_id, :body, :rate)
    end 
    
    def find_id
      @review = Review.find(params[:id])
    end 
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/edit.html.erb
<div class="review-edit-wrapper">
  <div class="container">
    <h3 class="text-center">レビュー内容の変更</h3>
    <%= form_for @review, url: tour_review_path do |f| %>
      <div class="review-form star">
        <dt><%= f.label :rate, "評価" %></dt>
        <dd><%= f.hidden_field :rate, class: 'review-star' %></dd>
      </div>
      <script>
      $('.star').raty({  //星表示のソース
        size     : 40,
        starOff:  '<%= asset_path('star-off.png') %>',
        starOn : '<%= asset_path('star-on.png') %>',
        starHalf: '<%= asset_path('star-half.png') %>',
        scoreName: 'review[rate]', //reviewモデルのrateカラムに値を保存する
        half: true,
      });
      </script>
      <div class="review-form">
        <dt><%= f.label :body, "レビュー内容" %></dt>
        <dd><%= f.text_field :body, class: 'review-common-form form-control' %></dd>
      </div>
      <%= f.submit "投稿", class: "btn btn-send" %>
    <% end %>
    

app/views/reviews/index.html.erb
<div class="review-index-wrapper">
  <div class="review-index-container container">
    <h3 class="text-center">レビュー一覧</h3>
    <div class="row  justify-content-center">
      <div class="col-sm-offset-3 col-sm-6">
        <% @review.each do |review| %>
          <div class="tour-index-list">
            <p>＜投稿者＞</p>
            <p><%= review.user.name %>さん</p>
            <div id="star-rate-<%= review.id %>"></div> <!-- Jsのidにreview.idを付けないとeachされない -->
            <script>
              $('#star-rate-<%= review.id %>').raty({
                size: 40,
                starOff:  '<%= asset_path('star-off.png') %>',
                starOn : '<%= asset_path('star-on.png') %>',
                starHalf: '<%= asset_path('star-half.png') %>',
                half: true,
                readOnly: true,
                score: <%= review.rate %>,
              });
            </script>
            <%= review.body %>
            <p><%= l review.created_at %></p>
            <div>
              <% if current_user.id == review.user_id %>
               <%= link_to "編集", edit_tour_review_path(review.tour_id, review.id) %>
               <%= link_to "削除", tour_review_path(review.tour_id, review.id), method: :delete %>
              <% end %>
            </div>
          </div>
        <% end %>
        <%= will_paginate @review, :previous_label => ' &lt 前へ', :next_label => '次へ &gt' %><br>
      </div>
    </div>
  </div>
</div>

app/views/reviews/new.html.erb
<div class="review-new-wrapper">
  <div class="container">
    <h3 class="page-title text-center">レビュー</h3>
    <div class="row  justify-content-center">
      <div class="col-sm-offset-4 col-sm-4">
        <p class="review-tour-title">ツアー名</p>
        <%= @review.tour.title %>
        <%= form_for @review, url: tour_reviews_path do |f| %>
          <%= f.hidden_field :tour_id, value: @review.tour_id %>
          <dl>
            <div class="review-form" id="star">
              <dt><%= f.label :rate, "評価" %></dt>
              <dd><%= f.hidden_field :rate, class: 'review-star' %></dd>
            </div>
            <script>
            $('#star').raty({  //星表示のソース
              size     : 40,
              starOff:  '<%= asset_path('star-off.png') %>',
              starOn : '<%= asset_path('star-on.png') %>',
              starHalf: '<%= asset_path('star-half.png') %>',
              scoreName: 'review[rate]', //reviewモデルのrateカラムに値を保存する
              half: true,
            });
            </script>
            <div class="review-form">
              <dt><%= f.label :body, "レビュー内容" %></dt>
              <dd><%= f.text_area :body, rows: 4, class: 'review-common-form form-control' %></dd>
            </div>
            </dl>
          <%= f.submit "投稿", class: "btn btn-send" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/reviews/show.html.erb
<div class="review-show-wrapper">
  <div class="container">
    <h3 class="page-title text-center">レビュー</h3>
    <div class="row  justify-content-center">
      <div class="col-sm-offset-3 col-sm-6">
        <div class="review-contents">
          <div class="review-tour">
            <P>＜ツアー名＞</P>
            <%= @review.tour.title %>
          </div>
          <div class="review-user">
            <p>＜レビュー投稿者＞</p>
            <p><%= @review.user.name %>さん</p>
          </div>
          <p>＜評価＞</p>
          <p><%= @review.rate %>点 </p>
          <div id="star-rate"></div>
          <script>
            $('#star-rate').raty({
              size: 40,
              starOff:  '<%= asset_path('star-off.png') %>',
              starOn : '<%= asset_path('star-on.png') %>',
              starHalf: '<%= asset_path('star-half.png') %>',
              half: true,
              readOnly: true,
              score: <%= @review.rate %>,
            });
          </script>
          <%= @review.body %>
          <p><%= l @review.created_at %></p>
        </div>
        <div class="revie-edit-btn">
          <% if current_user.id == @review.user_id %>
            <%= link_to "編集", edit_tour_review_path %>
            <%= link_to "削除", tour_review_path, method: :delete %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>