config/routes.rb
Rails.application.routes.draw do
  
  #中間テーブル(参加者)のアクション
  get 'user_tours/create'
  post 'user_tours/create'
  get 'user_tours/destroy'
  delete 'user_tours/destroy'
  
  #トップページアクション
  root 'pages#home'
  get 'pages/home'
  get 'pages/about'
  get 'pages/contact'
  
  #新規登録アクション
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  
  #問い合わせアクション
  get 'inquiries/new'
  get 'inquiries/create'
  get '/inquiries', to: 'inquiries#new'
  post '/inquiries', to: 'inquiries#create'
  
  #ログイン、ログアウトに関してのアクション
  get 'sessions/new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  #SNS認証ログインに関してのアクション
  get 'auth/:provider/callback', to: 'sessions#create'
  post 'auth/:provider/callback', to: 'sessions#create'
  
  #プロフィール画面に関してのアクション
  get 'users/:id/profiles', to: 'profiles#new', as: 'profiles_new'
  post 'users/:id/profiles', to: 'profiles#create'
  get 'users/:id/profile/show', to: 'profiles#show', as: 'profiles_show'
  get 'users/:id/profile/edit', to: 'profiles#edit', as: 'profiles_edit'
  patch 'users/:id/profile/edit', to: 'profiles#update'
  
  #ツアー検索一覧
  get '/tours', to: 'tours#index', as: 'all_tour'
  
  #ツアー詳細問い合わせアクション'
  get '/tours/:id/tour_contact', to: 'tour_contacts#new', as: 'tour_contacts_new'
  get '/tours/:id/tour_contact', to: 'tour_contacts#create'
  post '/tours/:id/tour_contact', to: 'tour_contacts#create', as: 'tour_contacts_create'
  
  #過去に参加したツアー一覧
  get '/users/:id/joined_past', to: 'users#joined_past', as: 'joined_past'
  
  #過去に開催したツアー一覧
  get '/users/:id/planned_past', to: 'users#planned_past', as: 'planned_past'
  
  resources :users
  
  resources :tours do
    resources :reviews
  end 
  
  namespace :admin do
    resources :users
  end 
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
  validates :src, presence: true
  
  belongs_to :tour
  
  #ツアー画像用
  mount_uploader :src, ImageUploader
  
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
  validates :name, length: { maximum: 50 }
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX }
                      
  validates :title, length: { maximum: 50 }
                      
  validates :message, presence: true, length: { maximum: 1000 }
end

app/models/profile.rb
class Profile < ApplicationRecord
  validates :user_id, presence: true, uniqueness:true
  validates :body, length: {maximum: 1000} 
  

  belongs_to :user
  
  mount_uploader :image, ImageUploader
  

  private
  
end 

app/models/review.rb
class Review < ApplicationRecord
  validates :user_id, presence: true
  validates :tour_id, presence: true
  validates :body, length: { maximum: 500 }
  
  validates :rate, numericality: {
    less_than_or_equal_to: 5,      #星評価は1~5
    greater_than_or_equal_to: 0.5
  }, presence: true
  
  belongs_to :tour
  belongs_to :user
  
  scope :id_index, -> (tour_id) {Review.where(tour_id)} #tour_idごとの一覧を表示する
end

app/models/tour.rb
class Tour < ApplicationRecord
  validates :user_id, presence: true
  validates :title, presence: true, length: { maximum: 30 }
  validates :detail, presence: true, length: { maximum: 1500 }
  validates :address, presence: true
  validate :tour_day #空白と過去の日付は指定できない。下部にメソッドあり
  
  #ツアー一覧はツアー開催日順に表示する
  default_scope -> { order(date: :asc) }
  
  
  #gmapについて
  geocoded_by :address #addressカラムを基準に緯度経度を算出する
  after_validation :geocode, if: :address_changed? #住所変更時に緯度経度も変更する
  
  belongs_to :user
  has_many :user_tours
  has_many :joined_users, through: :user_tours, source: 'user' #ツアーに参加するユーザーリスト
  has_many :tour_contacts
  has_many :reviews
  has_many :reviewed_users, through: :reviews, source: 'user' #レビューを書いたユーザーリスト
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true #削除フラグで削除できるようallow_destroy: trueをつける
  
  scope :from_today, -> {where("date > ?", Date.today)}
  
  #ツアー検索
  def self.search(search) #self.はTour.を意味する
    if search
      where(['title LIKE ?', "%#{search}%"]) #検索とaddressの部分一致を表示する
    else
      all
    end
  end
  
  def tour_day
    validate_date = Date.tomorrow
    if date == nil || date < validate_date.beginning_of_day
      errors.add(:date, "は明日以降を選択してください")
    end
  end 
end
 

app/models/tour_contact.rb
class TourContact < ApplicationRecord
  validates :name, length: { maximum: 50 }
  validates :tour_id, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX }
                      
  validates :message, presence: true, length: { maximum: 1000 }
                      
                      
  belongs_to :tour
  has_many :reviews
end

app/models/user.rb
class User < ApplicationRecord
  before_save :email_downcase, unless: :uid?
  
  validates :name, presence: true, unless: :uid?, length: { maximum: 50 }
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, unless: :uid?, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false } #一意性の確認と、{大文字小文字の区別をしないという設定}
  
  VALID_PASSWORD_REGEX = /\A[a-z0-9]{8,32}+\z/i   #半角英数字8-32文字               
  validates :password, presence: true, format: { with: VALID_PASSWORD_REGEX }, allow_nil: true, unless: :uid?
  has_secure_password
  
  has_one :profile, dependent: :destroy
  has_many :user_tours, dependent: :destroy
  has_many :tours, dependent: :destroy
  has_many :joined_tours, through: :user_tours, source: 'tour' #ユーザーが参加するツアーリスト
  accepts_nested_attributes_for :user_tours, allow_destroy: true  #親モデルの更新の時、子モデルもまとめて更新できるようにする
  
  scope :join_tours_from_today, -> (id) { User.find(id).joined_tours.where("date > ?", Date.today).limit(5)} #今日以降の参加予定ツアー
  scope :plan_tours_from_today, -> (id) { User.find(id).tours.where("date > ?", Date.today).limit(5)} #今日以降の開催予定ツアー
  scope :joined_tours_past, -> (id) { User.find(id).joined_tours.where("date < ?", Date.today)} #昨日以前の過去に参加したツアー
  scope :planned_tours_past, -> (id) { User.find(id).tours.where("date < ?", Date.today)} #昨日以前の過去に開催したツアー
  
  #アドミンページのユーザー検索
  def self.search(search) 
    if search
      where(['name LIKE ?', "%#{search}%"])   
    else  
      all  
    end  
  end
  
  
  #SNS認証ログイン
  def self.find_or_create_from_auth(auth)
    provider = auth[:provider]
    uid = auth[:uid]
    name = auth[:info][:name]
    
    self.find_or_create_by(provider: provider, uid: uid) do |user|
      user.name = name
    end
  end
  
  def email_downcase
    self.email = email.downcase
  end 
end

app/models/user_tour.rb
class UserTour < ApplicationRecord
  belongs_to :user
  belongs_to :tour
  
  validates :user_id, presence: true
  validates :tour_id, presence: true
  validates :user_id, :uniqueness => { :scope => :tour_id } #user_idとtour_idの組み合わせが重複しないように
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
   
end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/inquirys_helper.rb
module InquirysHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
  
  #ログインしているユーザーに関連付けられているプロフィールがあるか
  def has_profile?
    !current_user.profile.nil?
  end 
    
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
end

app/helpers/tours_helper.rb
module ToursHelper
  
end

app/helpers/user_tours_helper.rb
module UserToursHelper
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation">
    <ul>
    <% model.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="row">
    <div class="col-lg-12">
      <p>Copyright &#169; 2020 FREE WALKING TOUR JP All Rights Reserved. </p>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg">
    <% if logged_in? %>
      <%= link_to "FREE WALKING TOUR JP",user_path(current_user.id), class: "navbar-brand" %>
    <% else %>
      <%= link_to "FREE WALKING TOUR JP",root_path, class: "navbar-brand" %>
    <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <% if logged_in? %>
        <li><%= link_to "Home", user_path(current_user.id), class: "nav-item active" %></li>
      <% else %>
        <li><%= link_to "Home", root_path, class: "nav-item active" %></li>
      <% end %>
      
      <li><%= link_to "About", pages_about_path, class: "nav-item" %></li>
      <li><%= link_to "Contact", inquiries_new_path, class: "nav-item" %></li>
      
      <% if logged_in? %> <!--ログイン後に表示されるメニュー-->
        <% if has_profile? %>
          <li><%= link_to "Profile", profiles_show_path(current_user.id), class: "nav-item" %></li> <!--プロフィールデータがある場合はshowアクションへ-->
        <% else %>
          <li><%= link_to "Profile", profiles_new_path(current_user.id), class: "nav-item" %></li>　<!--プロフィールデータがなければnewアクションへ-->
        <% end %>
        <li><%= link_to "Admin Page", admin_users_path, class: "nav-item" if current_user.admin? %></li> <!--管理者の場合は管理者ページリンクを表示するへ-->
        <li><%= link_to "Log out", logout_path, method: :delete, class: "nav-item" %>
      <% else %>
        <li><%= link_to "Log in", login_path, class: "nav-item" %></li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FreeWalkingTour</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application' %>
    <meta name=”viewport” content=”width=device-width, initial-scale=1, user-scalable=yes”> <!--user-scalableは画面拡大ができるようにする -->
    
  </head>
  
  <body>
    <%= render 'layouts/header' %>
    <div class="main">
      <% flash.each do |message_type, message| %>  <!-- flashメッセージがある場合に表示させる -->
        <div class="alert alert-<%= message_type %>" role="alert"><%= message %></div>
      <% end %>
      <script>
        $(function() { //flashメッセージの設定
          $(".alert").fadeOut(4000);
        });
      </script>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="about-wrapper">
  <div class="about-container container">
    <div class="explanation-title">
      <h3>Free Walking Tourとは</h3>
      <div class="explanation-detail">
        <p>旅先で、のんびりと歩きながら地元のボランティアガイドさんが、その土地の歴史や魅力などを紹介するツアー。</p>
        <p>決められたツアー料金はなく、ツアーの最後に満足度に応じて直接ボランティアガイドさんへチップを渡します。</p>
        <p>途中参加、途中退場OK。用事がある方、満足できなかった方など、ツアー途中でも抜けることができます。</p>
        <p>※その際はボランティアガイドさんへチップを渡すのを忘れずに！</p>
      </div>
    </div>
    <div class="explanation-title">
      <h3>ボランティアガイドとは</h3> 
      <div class="explanation-detail">
        <p>この町の文化や歴史をぜひ知ってほしい！紹介したい！という地元のボランティアの方々です。</p>
        <p>地元で人気の美味しいお店や、絶景スポットなど、地元の人しか知らない場所も教えてくれるかもしれません。</p>
      </div>
    </div>
    <div class="explanation-title">
      <h3>チップって、いくら渡せばいいのかわからない！という方へ</h3>
      <p>ボランティアガイドさんへの感謝の気持ちとして、必ず300円～/人は渡しましょう。</p>
      <p>もちろん、上限はありません。楽しい満足なツアーでしたら、その分感謝の意味を込めて多く渡しましょう！</p>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="top-wrapper text-center">
  <div class="user-top-container container">
    <div class="top-title">
      <h1>FREE WALKING TOUR</h1>
      <h2>IN JAPAN</h2>
      <h1>ENJOY TOURS WITH THE LOCALS</h1>
    </div>
    <% unless logged_in? %>
      <div class="row justify-content-center">
        <div class="col-lg-2 col-md-3 col-sm-5 col-8">
          <%= link_to 'Sign up', signup_path, class: 'btn btn-block btn-pink' %>
        </div>
        <div class="col-lg-2 col-md-3 col-sm-5 col-8">
          <%= link_to 'Log in', login_path, class: 'btn btn-block btn-pink' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<div class="middle-wrapper">
  <div class="row justify-content-center">
    <div class="col-md-4 serach-prefecture">
      <h5>＜ツアー検索＞</h5>
      <h6>都道府県、または都市名を入力してください</h6>
      <%= form_tag(all_tour_path, method: :get) do %>
        <div class="tour-search-form">
          <%= text_field_tag :search, params[:search] %>
          <%= submit_tag "検索", :address => nil %>
        </div>
      <% end %>
    </div>
  </div>
</div>